scara_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - link_01_joint
    - link_02_joint
    - link_03_joint
    - link_04_joint
  gains:
    link_01_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_02_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_03_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_04_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
two_finger_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint
  gains:
    gripper_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1