controller_list:
  - name: scara_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - link_01_joint
      - link_02_joint
      - link_03_joint
      - link_04_joint
  - name: two_finger_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_joint