# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop

generic_hw_control_loop:
  loop_hz: 50 # 250 to emulate serial pause COMMAND_PERIOD 0.0055 , SERIAL_PAUSE 0.004
  cycle_time_error_threshold: 0.1

# Settings for ros_control hardware interface (used in generic_hw_interface.cpp)
hardware_interface:
   joints:
    - link_01_joint
    - link_02_joint
    - link_03_joint
    - link_04_joint
    - gripper_joint


# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 500

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
scara_arm_pos_JT_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - link_01_joint
    - link_02_joint
    - link_04_joint

scara_arm_eff_JT_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - link_03_joint
  gains:
    link_03_joint:
      p: 600
      d: 2
      i: 20
      i_clamp: 255

scara_arm_gripper_pos_JT_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_joint

scara_arm_pos_JGP_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - link_01_joint
    - link_02_joint
    - link_04_joint

scara_arm_eff_JP_controller:
  type: effort_controllers/JointPositionController
  joint: link_03_joint
  pid: {p: 600, i: 20, d: 2, i_clamp: 100}

scara_arm_gripper_pos_JP_controller:
  type: position_controllers/JointPositionController
  joint: gripper_joint