controller_list:
  - name: fake_scara_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - link_01_joint
      - link_02_joint
      - link_03_joint
      - link_04_joint
initial:  # Define initial robot poses per group
  - group: scara_arm
    pose: home