controller_list:
  - name: scara_arm_position_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - link_01_joint
      - link_02_joint
      - link_04_joint
  - name: scara_arm_effort_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - link_03_joint